#!/bin/bash

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

cd "$SCRIPTPATH/../terraform-kubernetes"

terraform apply -destroy -auto-approve

cd "$SCRIPTPATH/../terraform-eks"

terraform apply -destroy -auto-approve
