#!/bin/bash

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

if [ ! -f "$HOME/.aws/credentials" ] && [ -z $1 ]
then
    echo "Enter password" 1>&2
    exit 1;
else
	if [ ! -f "$HOME/.aws/credentials" ]
	then
		if [ -f "$SCRIPTPATH/authData.yaml" ]
		then
			while read -r line ; do
				name=`echo $line | awk -F "=" '{print $1}'`
				val=`echo $line | awk -F "=" '{print $2}'`
				export "$name"="$val"
			done < "$SCRIPTPATH/authData.yaml"
		else
			source "$SCRIPTPATH/setup" -p "$1"
		fi
	fi

	cd "$SCRIPTPATH/../terraform-helm"

	terraform apply -destroy -auto-approve

	cd "$SCRIPTPATH/../terraform-state"

	cp "$SCRIPTPATH/../move_local.tf" "$SCRIPTPATH/../terraform-state/state.tf"
	terraform init -migrate-state -force-copy
	terraform apply -destroy -auto-approve

	cd "$SCRIPTPATH"
	
	if [ ! -f "$HOME/.aws/credentials" ] && [ ! -f "$SCRIPTPATH/authData.yaml" ]
	then
		source "$SCRIPTPATH/setup" -u "$1"
	fi
fi
