apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.10.1
  nodeSets:
    - name: default
      count: 1
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            storageClassName: ebs-sc
            resources:
              requests:
                storage: 10Gi
      config:
        node.master: true
        node.data: true
        node.ingest: true
        node.store.allow_mmap: false