apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata: 
  name: kibana
spec:
  version: 7.10.1
  count: 1
  elasticsearchRef:
    name: quickstart
  config:
     server.basePath: "/logs"
     server.rewriteBasePath: true
  http:
    service:
      spec:
        type: ClusterIP
        ports:
          - port: 443
            targetPort: 5601
            protocol: TCP
  podTemplate:
    spec:
      containers:
        - name: kibana
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /logs/login
              port: 5601
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5